api/urls.py
# encoding: utf-8

from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('',views.index,name='index'),
]

cmdb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('asset/',include('asset.urls')),
    path('webanalysis/',include('webanalysis.urls')),
    #path('api/',include('api.urls')),
]

webanalysis/urls.py
# encoding: utf-8

from django.urls import path
from . import views

app_name = 'webanalysis'

urlpatterns = [
    path('',views.index,name='index'),
    path('upload/',views.upload,name='upload'),
    path('dist_status_code/',views.dist_status_code,name='dist_status_code'),
    path('trend_visit/',views.trend_visit,name='trend_visit')
]

webanalysis/models.py
from django.db import models
from django.db import connection
# Create your models here.

class AccessLogFile(models.Model):
    name = models.CharField(max_length=128, null=False, default='')
    path = models.CharField(max_length=1024, null=False, default='')
    created_time = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=0)

class AccessLog(models.Model):
    file_id = models.IntegerField(null=False, default=0)
    ip = models.GenericIPAddressField(null=False, default='0.0.0.0')
    url = models.CharField(max_length=1024, null=False, default='')
    status_code = models.IntegerField(default=0, null=False)
    access_time = models.DateTimeField(null=False)

    @classmethod
    def dist_status_code(cls,file_id):
        cursor = connection.cursor()
        cursor.execute('''
                            select status_code, count(*)
                            from webanalysis_accesslog
                            where file_id=%s
                            group by status_code
                        ''', (file_id, ))
        rt = cursor.fetchall()
        legend = []
        series = []
        for line in rt:
            legend.append(str(line[0]))
            series.append({"name" : str(line[0]), "value" : line[1]})

        return legend, series

    @classmethod
    def trend_visit(cls,file_id):
        cursor = connection.cursor()
        cursor.execute('''
                            select date_format(access_time, '%%Y-%%m-%%d %%H:00:00') as day, count(*) as cnt
                            from webanalysis_accesslog
                            where file_id = %s and access_time >= %s
                            group by day
                            order by day;
                        ''', (file_id, '1900-01-01'))
        rt = cursor.fetchall()
        xAxis = []
        series = []
        for line in rt:
            xAxis.append(line[0])
            series.append(line[1])

        return xAxis, series

webanalysis/views.py
# encoding: utf-8
import os, time, json
from functools import wraps
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from .models import AccessLogFile, AccessLog
# Create your views here.

def login_required(func):

    @wraps(func)
    def wrapper(request, *args, **kwargs):
        if request.session.get('user') is None:
            if request.is_ajax():
                return JsonResponse({'code' : 403, 'result' : []})
            return redirect('user:login')

        return func(request, *args, **kwargs)
    return wrapper

@login_required
def index(request):
    files = AccessLogFile.objects.filter(status=0).order_by('-created_time')[:10]
    return render(request, 'webanalysis/index.html',{"files" : files})

@login_required
def upload(request):
    log = request.FILES.get('log', None)
    if log:
        path = os.path.join(settings.BASE_DIR, 'media', 'uploads', str(time.time()))
        fhandler = open(path, 'wb')

        for chunk in log.chunks():
            fhandler.write(chunk)
        fhandler.close()

        obj = AccessLogFile(name=log.name, path=path)
        obj.save()

        path = os.path.join(settings.BASE_DIR, 'media', 'notices', str(time.time()))
        with open(path,'w') as fhandler:
            fhandler.write(json.dumps({'id' : obj.id, 'path' : obj.path}))

    return HttpResponse('upload')

@login_required
def dist_status_code(request):
    legend, series = AccessLog.dist_status_code(request.GET.get('id',0))
    print(legend, series)
    return JsonResponse({'code' : 200, 'result' : {"legend" : legend, 'series' : series}})

@login_required
def trend_visit(request):
    xAxis, series = AccessLog.trend_visit(request.GET.get('id',0))
    print(xAxis, series)
    return JsonResponse({'code' : 200, 'result' : {"xAxis" : xAxis, 'series' : series}})

webanalysis/templates/webanalysis/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}WEB日志分析{% endblock %}
{% block nav_webanalysis %}active{% endblock %}

{% block container %}
<div class="row">
	<div class="col-md-12">
		<form method="POST" enctype="multipart/form-data" action="{% url 'webanalysis:upload' %}">
			{% csrf_token %}
			<div class="form-group">
                <label class="form-label sr-only">上传文件</label>
                <input class="" type="file" name="log" />
            </div>
			<input class="btn btn-default" type="submit" value="upload">
		</form>
	</div>
</div>
<div class="row">
    <div class="col-md-6">
        <form class="form-group">
            <label class="form-label">文件选择</label>
            <select class="form-control" id="accesslog_file">
                {% for item in files %}
                    <option value="{{ item.id }}">
                        {{ item.name}}({{item.created_time}})
                    </option>
                {% endfor %}
            </select>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div id="dist-status-code" style="width: 100%; height:300px;">1</div>
    </div>
    <div class="col-md-6">
        <div id="trend-visit" style="width: 100%; height:300px;">2</div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div id="dist-geo" style="width: 100%; height:600px;">3</div>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="{% static 'echarts-2.2.7/build/dist/echarts-all.js' %}"></script>
{% endblock %}

{% block js %}

var chart_dist_status_code = echarts.init(document.getElementById('dist-status-code'));

var option_dist_status_code = {
    title : {
        text: '状态码分布',
        subtext: '',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient : 'vertical',
        x : 'left',
        data:[]
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {
                show: true, 
                type: ['pie', 'funnel'],
                option: {
                    funnel: {
                        x: '25%',
                        width: '50%',
                        funnelAlign: 'left',
                        max: 1548
                    }
                }
            },
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    series : [
        {
            name:'访问来源',
            type:'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[]
        }
    ]
};

var chart_trend_visit = echarts.init(document.getElementById('trend-visit'));

option_trend_visit = {
    title : {
        text: '每小时网站访问量',
        subtext: '',
        x:'center'
    },
    tooltip : {
        trigger: 'axis',
        axisPointer : {
            type : 'shadow'
        }
    },
    legend: {
        x: 'left',
        orient : 'vertical',
        data:['访问次数']
    },
    toolbox: {
        show : true,
        orient: 'vertical',
        x: 'right',
        y: 'center',
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar', 'stack', 'tiled']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            data : []
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'访问次数',
            type:'bar',
            data:[]
        }
    ]
};
                    
function reload() {
    console.log('reload')
    var id = jQuery('#accesslog_file').val();
    reload_dist_status_code(id);
    reload_trend_visit(id);
    reload_dist_geo(id);
}
    
    

function reload_dist_status_code(id) {
    jQuery.get("{% url 'webanalysis:dist_status_code' %}", {"id" : id}, function(result) {
        console.log(result)
        if(200 === result['code']) {
            chart_dist_status_code.clear();
            option_dist_status_code['legend']['data'] = result['result']['legend'];
            option_dist_status_code['series'][0]['data'] = result['result']['series'];
            chart_dist_status_code.setOption(option_dist_status_code);
        }
    },'json');
}


function reload_trend_visit(id) {
    jQuery.get("{% url 'webanalysis:trend_visit' %}", {"id" : id}, function(result) {
        console.log(result)
        if(200 === result['code']) {
            chart_trend_visit.clear();
            option_trend_visit['xAxis'][0]['data'] = result['result']['xAxis'];
            option_trend_visit['series'][0]['data'] = result['result']['series'];
            chart_trend_visit.setOption(option_trend_visit);
        }
    },'json');
}

function reload_dist_geo(id) {
    
}               

reload()

jQuery('#accesslog_file').on('change', function () {
    reload();
});
{% endblock %}