api/urls.py
# encoding: utf-8

from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('',views.index,name='index'),
]

asset/urls.py
# encoding: utf-8

from django.urls import path
from . import views

app_name = 'asset'

urlpatterns = [
    path('',views.index,name='index'),
    path('list/ajax/', views.list_ajax, name='list_ajax'),
    path('resource/ajax/', views.resource_ajax, name='resource_ajax'),
    path('update/ajax/', views.update_ajax, name='update_ajax'),
    path('list_info/ajax/', views.list_info_ajax, name='list_info_ajax')
]

cmdb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('asset/',include('asset.urls')),
    path('webanalysis/',include('webanalysis.urls')),
    #path('api/',include('api.urls')),
]

asset/models.py
#encoding: utf-8

from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
import datetime


class Host(models.Model):
    name = models.CharField(max_length=128, null=False, default='')
    ip = models.GenericIPAddressField(null=False, default='0.0.0.0')
    mac = models.CharField(max_length=32, null=False, default='')
    os = models.CharField(max_length=64, null=False, default='')
    arch = models.CharField(max_length=16, null=False, default='')
    mem = models.BigIntegerField(null=False, default=0)
    cpu = models.IntegerField(null=False, default=0)
    disk = models.CharField(max_length=512, null=False, default='{}')

    sn = models.CharField(max_length=128, null=False, default='')
    user = models.CharField(max_length=128, null=False, default='')
    remark = models.TextField(null=False, default='')
    purchase_time = models.DateTimeField(null=False)
    over_insurance_time = models.DateTimeField(null=False)

    created_time = models.DateTimeField(null=False, auto_now_add=True)
    last_time = models.DateTimeField(null=False)

    @classmethod
    def create_or_replace(cls, ip, name, mac, os, arch, mem, cpu, disk):
        obj = None
        try:
            obj = cls.objects.get(ip=ip)
        except ObjectDoesNotExist as e:
            obj = cls()
            obj.ip = ip
            obj.purchase_time = timezone.now().strftime('%Y-%m-%d %H:%M')
            obj.over_insurance_time = timezone.now().strftime('%Y-%m-%d %H:%M')

        obj.name = name
        obj.mac = mac
        obj.os = os
        obj.arch = arch
        obj.mem = mem
        obj.cpu = cpu
        obj.disk = disk

        obj.last_time = timezone.now().strftime('%Y-%m-%d %H:%M')
        obj.save()
        return obj

    def as_dict(self):
        rt = {}
        for k, v in self.__dict__.items():
            if isinstance(v, (int, float, bool, str, datetime.datetime)):
                rt[k] = v
        return rt

class Resource(models.Model):
    ip = models.GenericIPAddressField(null=False, default='0.0.0.0')
    cpu = models.FloatField(null=False, default=0)
    mem = models.FloatField(null=False ,default=0)
    created_time = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    @classmethod
    def create_obj(cls, ip, cpu, mem):
        resource = Resource()
        resource.ip = ip
        resource.cpu = cpu
        resource.mem = mem
        resource.save()
        return resource

asset/views.py
#encoding: utf-8

from datetime import timedelta,datetime
from functools import wraps
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse

from .models import Host, Resource
# Create your views here.

def login_required(func):

    @wraps(func)
    def wrapper(request, *args, **kwargs):
        if request.session.get('user') is None:
            if request.is_ajax():
                return JsonResponse({'code' : 403, 'result' : []})
            return redirect('user:login')

        return func(request, *args, **kwargs)
    return wrapper

@login_required
def index(request):
    return render(request, 'asset/index.html')

@login_required
def list_ajax(request):
    result= [host.as_dict() for host in Host.objects.all()]
    return JsonResponse({'code' : 200, 'result' : result})

@login_required
def list_info_ajax(request):
    try:
        _id = request.GET.get('id',0)
        #print(_id)
        host=Host.objects.get(id=_id).as_dict()
        #print(host)
        return JsonResponse({'code' : 200, 'result' : host})
    except BaseException as e:
        return JsonResponse({'code' : 404, 'result' : []})

@login_required
def resource_ajax(request):
    try:
        _id = request.GET.get('id',0)
        host=Host.objects.get(id=_id)
        start_time = datetime.now() - timedelta(hours=6)
        resources = Resource.objects.filter(ip=host.ip,created_time__gte=start_time).order_by('created_time')

        xAxis = []
        cpu_datas = []
        mem_datas = []

        for resource in resources:
            xAxis.append(resource.created_time.strftime('%Y-%m-%d %H:%M'))
            cpu_datas.append(resource.cpu)
            mem_datas.append(resource.mem)
        return JsonResponse({'code' : 200, 'result' : {'xAxis' : xAxis, 'cpu_datas' : cpu_datas, 'mem_datas' : mem_datas}})
    except BaseException as e:
        return JsonResponse({'code' : 403, 'result' : []})

@login_required
def update_ajax(request):
    pass

asset/templates/asset/index.html
{% extends "base.html" %}

{% block title %}资产管理{% endblock %}
{% block nav_asset %}active{% endblock %}
{% block container %}
<table id="table_asset" class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>名称(IP)</th>
            <th>操作系统</th>
            <th>架构</th>
            <th>内存</th>
            <th>CPU</th>
            <th>磁盘</th>
            <th>发现时间</th>
            <th>最后发现时间</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<!-- /.modal -->
<div class="modal fade" id="dialog-dog-asset" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">资源监控</h4>
      </div>
      <div class="modal-body">
         <div id="main" style="width: 850px;height:400px;"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- /.modal -->
<!-- Modal-edit-asset -->
<div class="modal fade" id="dialog-edit-asset" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">修改主机信息</h4>
      </div>
      <div class="modal-body">
        <form class="from-edit-asset">
            <label class="sr-only">名称</label>
            <input type="text" id="name" name="name" class="form-control" placeholder="名称"><br/>
            <label class="sr-only">操作系统</label>
            <input type="text" id="os" name="os" class="form-control" placeholder="操作系统"><br/>
            <label class="sr-only">架构</label>
            <input type="text" id="arch" name="arch" class="form-control" placeholder="架构"><br/>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary btn-save-asset">保存</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}

var table = jQuery('#table_asset').DataTable({
    "language": {
        "processing": "处理中...",
        "lengthMenu": "显示 _MENU_ 项结果",
        "zeroRecords": "没有匹配结果",
        "info": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
        "infoEmpty": "显示第 0 至 0 项结果，共 0 项",
        "infoFiltered": "(由 _MAX_ 项结果过滤)",
        "infoPostFix": "",
        "search": "搜索:",
        "searchPlaceholder": "搜索...",
        "url": "",
        "emptyTable": "表中数据为空",
        "loadingRecords": "载入中...",
        "infoThousands": ",",
        "paginate": {
            "first": "首页",
            "previous": "上页",
            "next": "下页",
            "last": "末页"
        },
        "aria": {
            paginate: {
                first: '首页',
                previous: '上页',
                next: '下页',
                last: '末页'
            },
            "sortAscending": ": 以升序排列此列",
            "sortDescending": ": 以降序排列此列"
        },
        "decimal": "-",
        "thousands": "."
    },
    ajax : {
        url : '{% url "asset:list_ajax" %}',
        dataSrc: 'result',
    },
    columns : [
        {
            "data" : function(row, type, set, meta) {
                return row['name'] + '(' + row['ip'] + ')';
            }
        },
        {
            "data" : "os"
        },
        {
            "data" : "arch"
        },
        {
            "data" : "mem"
        },
        {
            "data" : "cpu"
        },
        {
            "data" : "disk"
        },
        {
            "data" : "created_time"
        },
        {
            "data" : "last_time"
        },
        {
            "data" : function(row) {
                return '<a class="btn btn-success btn-xs btn-edit-asset" href="javascript:void(0)" data-id="' + row['id'] + '">编辑</a>' + '<a class="btn btn-primary btn-xs btn-dog-asset" href="javascript:void(0)" data-id="' + row['id'] + '">监控</a>' +
                '<a class="btn btn-danger btn-xs btn-delete-asset" data-id="' + row['id'] + '" href="javascript:void(0)">删除</a>';
            }
        },
    ]
});


// edit-asset
jQuery('#table_asset').on('click', '.btn-edit-asset', function() {
    var id = jQuery(this).attr('data-id');
    $('#dialog-edit-asset').modal({show:true});
    $.get("{% url 'asset:list_info_ajax' %}", {'id' : id, '_' : (new Date()).getTime()} ,function(result) {
        console.log(result);
        $('#name').val(result['result']['name']);
        $('#os').val(result['result']['os']);
        $('#arch').val(result['result']['arch']);
    });

    table.ajax.reload(null, false);
});

// save-asset
$('.btn-save-asset').on('click', function() {
    var data = $('.from-edit-asset').serializeArray();
});

// 图形
var chart_resource_option = {
    title : {
        text: 'CPU,内存监控',
        subtext: '',
        x:'center'
    },
    tooltip : {
        trigger: 'axis',
        axisPointer : {
            type : 'shadow'
        }
    },
    legend: {
        x: 'left',
        orient : 'vertical',
        data:['CPU','mem']
    },
    toolbox: {
        show : true,
        orient: 'vertical',
        x: 'right',
        y: 'center',
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar', 'stack', 'tiled']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            data : []
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
                {
                    name:'CPU',
                    type:'line',
                    smooth: true,
                    stack: 'CPU',
                    data:[]
                },
                {
                    name:'mem',
                    type:'line',
                    smooth: true,
                    stack: 'mem',
                    data:[]
                }
            ]
};


function reload_resource_chart(id) {
    $.get('{% url 'asset:resource_ajax' %}',{'id' : id, '_' : (new Date()).getTime()},function(result) {
            if(result['code'] == 200) {
                // 从后端获取数据
                var chart_resource = echarts.init(document.getElementById('main'));
                chart_resource_option['xAxis']['data'] = result['result']['xAxis'];
                chart_resource_option['series'][0]['data'] = result['result']['cpu_datas'];
                chart_resource_option['series'][1]['data'] = result['result']['mem_datas'];
                // 使用刚指定的配置项和数据显示图表。
                chart_resource.setOption(chart_resource_option);
                console.log(chart_resource_option['xAxis']['data']);
            }
        }, 'json');
    }

var th = null
 //btn-dog-asset
$('#table_asset').on('click', '.btn-dog-asset', function(){
    var id = id = jQuery(this).data('id');

    reload_resource_chart(id);
    if(th === null)
        th = setInterval(function() {
            reload_resource_chart(id);
        },30*1000);


    $('#dialog-dog-asset').modal({show:true});
});




$('#dialog-dog-asset').on('hidden.bs.modal',function(e) {
    if(th !== null) {
    clearInterval(th);
    th = null;
}
});



jQuery('#table_asset').on('click', '.btn-delete-asset', function() {
    console.log('删除' + jQuery(this).attr('data-id'));
    table.ajax.reload(null, false);
});
{% endblock %}