api/urls.py
# encoding: utf-8

from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('',views.index,name='index'),
]

cmdb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('asset/',include('asset.urls')),
    path('webanalysis/',include('webanalysis.urls')),
    #path('api/',include('api.urls')),
]

user/urls.py
# encoding: utf-8

from django.urls import path
from . import views


app_name = 'user'


urlpatterns = [
    path('',views.index,name='index'),
    path('login/',views.login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('delete/',views.delete,name='delete'),
    path('user_info/',views.user_info,name='user_info'),
    path('update/',views.update,name='update'),
    path('create/',views.create,name='create'),
    path('change_password/',views.change_password,name='change_password'),
    path('create/ajax',views.create_ajax,name='create_ajax'),
    path('delete/ajax',views.delete_ajax,name='delete_ajax'),
    path('change_password_ajax/',views.change_password_ajax,name='change_password_ajax'),
    path('list/ajax',views.list_ajax,name='list_ajax')

]

user/models.py
# encoding: utf-8

from django.db import models

class User(models.Model):
    name = models.CharField(max_length=32, null=False, default='') # => name varchar(32) not null default ''
    password = models.CharField(max_length=512, null=False, default='')
    age = models.IntegerField(null=False, default=0) # => age int not null default 0
    tel = models.CharField(max_length=32, null=False, default='')
    sex = models.BooleanField(null=False, default=True)
    create_time = models.DateTimeField(null=False)
    addr = models.CharField(max_length=120, null=False, default='')

    @classmethod
    def delete_user(cls,uid):
        return cls.objects.filter(id=uid).delete()

    def as_dict(self):
        return{
            'id': self.id,
            'name': self.name,
            'age' : self.age,
            'tel' : self.tel,
            'sex' : self.sex,
            'password' : self.password,
            'addr' : self.addr
        }



class Log_anlyze(models.Model):
    IP = models.CharField(max_length=255, null=False, default='')
    URL = models.CharField(max_length=512, null=False, default='')
    STATUS = models.CharField(max_length=32, null=False, default='')
    TIME = models.DateTimeField(null=False)

user/views.py
# encoding: utf-8
from functools import wraps
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse
from datetime import datetime
# Create your views here.
from .models import User
from .validdator import UserValidator

def login_required(func):

    @wraps(func)
    def wrapper(request, *args, **kwargs):
        if request.session.get('user') is None:
            if request.is_ajax():
                return JsonResponse({'code' : 403, 'result' : []})
            return redirect('user:login')

        return func(request, *args, **kwargs)
    return wrapper

curr_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
@login_required
def index(request):
    return render(request, 'user/index.html')

@login_required
def list_ajax(request):
    result= [user.as_dict() for user in User.objects.all()]
    return JsonResponse({'code' : 200, 'result' : result})


def login(request):
    if 'GET' == request.method:
        return render(request,'user/login.html')
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = UserValidator.valid_login(username,password)
        if user:
            request.session['user']=user.as_dict()
            return redirect('user:index')
        else:
            return render(request,'user/login.html',{'name': username, 'errors':{'default':'用户名或密码错误'}})


def user_logout(request):
    request.session.flush()
    return redirect('user:login')

@login_required
def delete(request):
    uid = request.GET.get('uid')
    if request.session.get('user')['name'] == 'Admin':
        if uid.isdigit():
            User.delete_user(uid)
        return redirect('user:index')
    else:
        return render(request,'user/index.html',{'errors':'你没有此操作权限', 'curr_time':curr_time, 'users':User.objects.all()})

@login_required
def user_info(request):
    uid = request.GET.get('uid','')
    if request.session.get('user')['id'] == uid or request.session.get('user')['name'] == 'Admin':
        return render(request,'user/user_info.html',{'user':User.objects.get(id=uid)})
    else:
        return render(request,'user/index.html',{'errors':'你没有此操作权限', 'curr_time':curr_time, 'users':User.objects.all()})


@login_required
def update(request):
    user,is_valid,error = UserValidator.valid_update_user(request.POST)
    if is_valid:
        user.save()
        return redirect('user:index')
    else:
        return render(request,'user/user_info.html',{'user' : user, 'errors' : error})

@login_required
def create(request):
    if request.session.get('user')['name'] != 'Admin':
        return render(request,'user/index.html',{'errors':'你没有此操作权限', 'curr_time':curr_time, 'users':User.objects.all()})
    if 'GET' == request.method:
        return render(request,'user/create.html')
    else:
        is_valid,user,error = UserValidator.valid_create_user(request.POST)
        if is_valid:
            user.save()
            return redirect('user:index')
        else:
            return render(request,'user/create.html',{'errors':error})


def create_ajax(request):
    if not request.session.get('user'):
        return JsonResponse({'code':403, 'errors':{'permission':'未登录'}})
    if request.session.get('user')['name'] != 'Admin':
        return JsonResponse({'code':403, 'errors':{'permission':'你没有此操作权限'}})
    else:
        is_valid,user,error = UserValidator.valid_create_user(request.POST)
        if is_valid:
            user.save()
            return JsonResponse({'code':200})
        else:
            return JsonResponse({'code':400, 'errors':error})


def change_password(request):
    uid = request.session.get('user')['id']
    if not request.session.get('user'):
        return redirect('user:login')
    if 'GET' == request.method:
        return render(request,'user/change_password.html')
    else:
        is_valid,user,errors = UserValidator.valid_cp(request.POST,uid)
        if is_valid:
            user.save()
            return redirect('user:index')
        else:
            return render(request,'user/change_password.html',{'errors':errors})


def change_password_ajax(request):
    uid = request.session.get('user')['id']
    if not request.session.get('user'):
        return JsonResponse({'code':403, 'errors':{'permission':'未登录'}})
    else:
        is_valid,user,errors = UserValidator.valid_cp(request.POST,uid)
        if is_valid:
            user.save()
            return JsonResponse({'code' : 200})
        else:
            return JsonResponse({'code' : 400, 'errors' : errors})


def delete_ajax(request):
    if not request.session.get('user'):
        return JsonResponse({'code':403, 'errors':{'permission':'未登录'}})
    uid = request.GET.get('id')
    if request.session.get('user')['name'] == 'Admin':
        if uid.isdigit():
            User.delete_user(uid)
            return JsonResponse({'code':200})
    else:
        return JsonResponse({'code':403, 'errors':{'permission':'你没有此操作权限'}})

user/templates/user/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>用户管理系统</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'common.css' %}">
  </head>

  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">用户管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/user/index">Home</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">{{ request.session.user.name }}</a></li>
            <li><a href="/user/logout">退出登录</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <form action="{% url 'user:change_password' %}" method="POST">
        <h2 class="form-signin-heading">修改密码</h2>
            {% if errors %}
                {% for key,error in errors.items %}
                    {{error}}
                {% endfor %}
            {% endif %}
        {% csrf_token %}
        <label for="inputoldpassword" class="sr-only">请输入旧密码:</label>
        <input type="password" name="old_password" class="form-control" placeholder="旧密码" ><br/>
        <label for="inputnewpassword" class="sr-only">请输入新密码: </label>
        <input type="password" name="new1_password" class="form-control" placeholder="新密码" ><br/>
        <label for="inputnewpassword" class="sr-only">再输入新密码: </label>
        <input type="password" name="new2_password" class="form-control" placeholder="再输一次新密码" ><br/>
        <input type="submit" class="btn btn-lg btn-primary btn-block" name="change_password" value="确认修改">
      </div>
        <footer class="footer">
          <p>&copy; 2018 NikoZhang, Inc.</p>
        </footer>
    </div> <!-- /container -->
  </body>
</html>

user/templates/user/create.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>用户管理系统</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'common.css' %}">
  </head>

  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">用户管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/user/index">Home</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">{{ request.session.user.name }}</a></li>
            <li><a href="/user/logout">退出登录</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <p class="bg-danger">
            {% if errors %}
                {% for key,error in errors.items %}
                    {{ error }}
                    <br/>
                {% endfor %}
                <br/>
            {% endif %}
        </p>
    <form action="{% url 'user:create' %}" method="POST">
        <label class="sr-only">用户姓名</label>
        <input type="text" name="username" value="" class="form-control" placeholder="用户名"/><br />
        <label class="sr-only">年龄</label>
        <input type="text" name="age" value="" class="form-control" placeholder="年龄"/><br />
        性别：
            <label class="radio-inline">
                <input id="inlineRadio1" type="radio" name="sex" value="1"
                {% if user.sex != 0%} checked="checked" {% endif %}/> 男
            </label>
            <label class="radio-inline">
                <input id="inlineRadio2" type="radio" name="sex" value="0"
                {% if user.sex == 0%} checked="checked" {% endif %}/> 女
            </label>
        <br /><br />
        <label class="sr-only">联系方式</label>
        <input type="text" name="tel" value="" class="form-control" placeholder="联系方式"/><br />
        <label class="sr-only">输入密码</label>
        <input type="password" name="password1" value="" class="form-control" placeholder="输入密码"/><br />
        <label class="sr-only">确认密码</label>
        <input type="password" name="password2" value="" class="form-control" placeholder="确认密码"/><br />
        <input class="btn btn-xs btn-success" type="submit" name="create" value="创建用户" /><br />
    {% csrf_token %}
    </form>
      </div>
        <footer class="footer">
          <p>&copy; 2018 NikoZhang, Inc.</p>
        </footer>
    </div> <!-- /container -->

  </body>
</html>

user/templates/user/index.html
{% extends "base.html" %}

{% block title %}用户管理{% endblock %}
{% block nav_user %}active{% endblock %}
{% block li_create %}<li><a class="btn-create-user"href="javascript:void(0)">添加用户</a></li>{% endblock %}
{% block li_changepassword %}<li><a class="btn-change-password" href="javascript:void(0)">修改密码</a></li>{% endblock %}
{% block container %}
<p class="bg-danger">
    {% if errors %}
        {% for error in errors %}
            {{error}}
        {% endfor %}
    {% endif %}
</p>
<table id="Table_user" class="table table-hover table-bordered table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>年龄</th>
            <th>性别</th>
            <th>联系方式</th>
            <th>所在地</th>
            <th>操作方式</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
</div> <!-- /container -->
{% endblock %}

{% block dialogs %}
    <!-- Modal-create-user -->
    <div class="modal fade" id="dialog-create-user" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">用户创建</h4>
          </div>
          <div class="modal-body">
            <form class="from-create-user">
                <label class="sr-only">用户姓名</label>
                <input type="text" name="username" value="" class="form-control" placeholder="用户名"/><br />
                <label class="sr-only">年龄</label>
                <input type="text" name="age" value="" class="form-control" placeholder="年龄"/><br />
                性别：
                    <label class="radio-inline">
                        <input id="inlineRadio1" type="radio" name="sex" value="1"
                        checked="checked"/> 男
                    </label>
                    <label class="radio-inline">
                        <input id="inlineRadio2" type="radio" name="sex" value="0"/> 女
                    </label>
                <br /><br />
                <label class="sr-only">联系方式</label>
                <input type="text" name="tel" value="" class="form-control" placeholder="联系方式"/><br />
                <label class="sr-only">输入密码</label>
                <input type="password" name="password1" value="" class="form-control" placeholder="输入密码"/><br />
                <label class="sr-only">确认密码</label>
                <input type="password" name="password2" value="" class="form-control" placeholder="确认密码"/><br />
            {% csrf_token %}
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            <button type="button" class="btn btn-primary btn-save-user">保存</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal-change-password -->
    <div class="modal fade" id="dialog-change-password" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">修改密码</h4>
          </div>
          <div class="modal-body">
            <form class="from-change-password">
                  {% if errors %}
                      {% for key,error in errors.items %}
                          {{error}}
                      {% endfor %}
                  {% endif %}
                {% csrf_token %}
                <label for="inputoldpassword" class="sr-only">请输入旧密码:</label>
                <input type="password" name="old_password" class="form-control" placeholder="旧密码" ><br/>
                <label for="inputnewpassword" class="sr-only">请输入新密码: </label>
                <input type="password" name="new1_password" class="form-control" placeholder="新密码" ><br/>
                <label for="inputnewpassword" class="sr-only">再输入新密码: </label>
                <input type="password" name="new2_password" class="form-control" placeholder="再输一次新密码" ><br/>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            <button type="button" class="btn btn-primary btn-save-password">保存</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

    <!-- script -->
{% block js %}
  $('#Table_user').DataTable({
      "language": {
          "processing": "处理中...",
          "lengthMenu": "显示 _MENU_ 项结果",
          "zeroRecords": "没有匹配结果",
          "info": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
          "infoEmpty": "显示第 0 至 0 项结果，共 0 项",
          "infoFiltered": "(由 _MAX_ 项结果过滤)",
          "infoPostFix": "",
          "search": "搜索:",
          "searchPlaceholder": "搜索...",
          "url": "",
          "emptyTable": "表中数据为空",
          "loadingRecords": "载入中...",
          "infoThousands": ",",
          "paginate": {
              "first": "首页",
              "previous": "上页",
              "next": "下页",
              "last": "末页"
          },
          "aria": {
              paginate: {
                  first: '首页',
                  previous: '上页',
                  next: '下页',
                  last: '末页'
              },
              "sortAscending": ": 以升序排列此列",
              "sortDescending": ": 以降序排列此列"
          },
          "decimal": "-",
          "thousands": "."
      },

      ajax : {
            url : '{% url "user:list_ajax" %}',
            dataSrc: 'result',
        },

      columns : [
        {
            "data" : function(row, type, set, meta) {
                return row['id'];
            }
        },
        { "data" : "name" },
        { "data" : "age" },
        { "data" : "sex" },
        { "data" : "tel" },
        { "data" : "addr" },
        { "data" : function(row) {
            return '<a class="btn btn-sm btn-warning" href="javascript:void(0)" data-id="' + row['id'] + '">修改</a>' + '<a class="btn btn-sm btn-danger btn-delete-user" href="javascript:void(0)" data-id="' + row['id'] + '">删除</a>'
          }
        },
      ]


  });

  //btn-change-password
  $('.btn-change-password').on('click', function() {
    $('#dialog-change-password').modal({show:true});
  });

  //btn-save-password
  $('.btn-save-password').on('click', function() {
    var data = $('.from-change-password').serializeArray();
    console.log(data);
    $.post("{% url 'user:change_password_ajax' %}", data ,function(result) {
        console.log(result);

        if(result['code'] == 200) {
            swal({
              title: '创建成功！',
              type: 'success',
              timer: 2000
            },function() {
                      //关闭sweetalert
                      swal.close();
                      /*刷新table*/
                      window.location.reload()
                  });
        }

        else if(result['code'] == 400) {
            var errors = []
            $.each(result['errors'], function(k,v) {
              errors.push(v)
            })
            swal(
              '验证失败!',
              errors.join('\n'),
              'error'
            )
        }

        else if(result['code'] == 403) {
            var errors = []
            jQuery.each(result['errors'], function(k,v) {
              errors.push(v)
            })
            swal({
                  title: errors.join('\n'),
                  text: '2秒后自动关闭并返回。',
                  timer: 2000
                },function() {
                      //关闭sweetalert
                      swal.close();
                      /*刷新table*/
                      window.location.reload()
                    });
        }

    });
  });

  //btn-create-user
  $('.btn-create-user').on('click',function(){
    console.log(jQuery('#dialog-create-user').length);
    $('#dialog-create-user').modal({show:true});
  });


  $('.btn-save-user').on('click',function() {
    var data = $('.from-create-user').serializeArray();
    console.log(data);
    jQuery.post("{% url 'user:create_ajax' %}", data, function(result) {
      console.log(result);
      if(result['code'] == 200) {
        swal({
              title: '创建成功！',
              type: 'success',
              timer: 2000
            },function() {
                      //关闭sweetalert
                      swal.close();
                      /*刷新table*/
                      window.location.reload()
                  });
        //$('#dialog-create-user').modal('hide');
        //window.location.reload()
      }
      else if(result['code'] == 400) {
        var errors = []
        jQuery.each(result['errors'], function(k,v) {
          errors.push(v)
        })
        swal(
              '验证失败!',
              errors.join('\n'),
              'error'
            )
      }
      else if(result['code'] == 403) {
        var errors = []
        jQuery.each(result['errors'], function(k,v) {
          errors.push(v)
        })
        swal({
                  title: errors.join('\n'),
                  text: '2秒后自动关闭并返回。',
                  timer: 2000
              },function() {
                      //关闭sweetalert
                      swal.close();
                      /*刷新table*/
                      window.location.reload()
                  });
      }
    },'json');
  });


  //btn-delete-user
  $('body').on('click', '.btn-delete-user', function() {
    var id = jQuery(this).attr('data-id');
    swal({
      title: "确定删除吗？",
      text: "",
      type: "warning",
      showCancelButton: true,
      confirmButtonColor: "#DD6B55",
      confirmButtonText: "确定删除！",
      cancelButtonText: "取消删除！",
      closeOnConfirm: false,
      closeOnCancel: true
    },
    function(){
        //提交ajax删除数据
        jQuery.get("{% url 'user:delete_ajax' %}", {'id' : id}, function(result) {
          console.log(result);
          if(result['code'] == 200) {
              swal({
                  title: "成功",
                  text: "",
                  type: "success",
                  closeOnConfirm: false
                }, function() {
                    //关闭sweetalert
                    swal.close();
                    /*刷新table*/
                    window.location.reload()
                });
          } else if(result['code'] == 400) {
              var errors = [];
              jQuery.each(result['errors'], function(k, v) {
                  errors.push(v);
              });
              swal("验证失败:", errors.join('\n'),"error")
          } else if(result['code'] == 403) {
              swal({
                  title: "未登录",
                  text: "",
                  timer: 2000,
                  showConfirmButton: false
              });
          }
        }, 'json');
    });
});
{% endblock %}

user/templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <title>用户管理</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'common.css' %}">
  </head>
  <body>
    <div class="container">
      <form class="form-signin" action="{% url 'user:login' %}" method="POST">
        <h2 class="form-signin-heading">用户管理系统</h2>
            {% if errors %}
                {% for key,error in errors.items %}
                    <div class="alert alert-danger" role="alert">{{error}}<br></div>
                {% endfor %}
            {% endif %}
            {% csrf_token %}
        <label for="inputEmail" class="sr-only">用户名</label>
        <input type="text" id="username" class="form-control" placeholder="用户名" name="username" value="{{ name }}">
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password" value="">
        <button class="btn btn-lg btn-primary btn-block" type="submit">登陆</button>
      </form>

    </div>
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
  </body>
</html>

user/templates/user/user_info.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>用户管理系统</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'common.css' %}">
  </head>

  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">用户管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/user/index">Home</a></li>
            <li><a href="/user/change_password">修改密码</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">{{ request.session.user.name }}</a></li>
            <li><a href="/user/logout">退出登录</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <p class="bg-danger">
            {% if errors %}
                {% for key,error in errors.items %}
                    {{ error }}<br/>
                {% endfor %}
            {% endif %}
        </p>
    <form action="{% url 'user:update' %}" method="POST">
        <input type="hidden" name="uid" value="{{ user.id }}">
        <label>用户名</label>
        <input type="text" name="username" value="{{ user.name }}" class="form-control" placeholder="用户名"/><br />
        <label>年龄</label>
        <input type="text" name="age" value="{{ user.age }}" class="form-control" placeholder="年龄"/><br />
        性别：
            <label class="radio-inline">
                <input id="inlineRadio1" type="radio" name="sex" value="1"
                {% if user.sex != 0%} checked="checked" {% endif %}/> 男
            </label>
            <label class="radio-inline">
                <input id="inlineRadio2" type="radio" name="sex" value="0"
                {% if user.sex == 0%} checked="checked" {% endif %}/> 女
            </label>
        <br /><br />
        <label>联系方式</label>
        <input type="text" name="tel" value="{{ user.tel }}" class="form-control" placeholder="联系方式""/><br />
        <label>所在地</label>
        <input type="text" name="addr" value="{{ user.addr }}" class="form-control" placeholder="所在地"/><br />
        <input type="submit" name="update" value="修改信息" class="btn btn-xs btn-success"/>
        {% csrf_token %}
    </form>
</body>
</html>