api/urls.py
# encoding: utf-8

from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('',views.index,name='index'),
]

asset/urls.py
# encoding: utf-8

from django.urls import path
from . import views

app_name = 'asset'

urlpatterns = [
    path('',views.index,name='index'),
    path('list/ajax/', views.list_ajax, name='list_ajax'),
    path('resource/ajax/', views.resource_ajax, name='resource_ajax'),
    path('update/ajax/', views.update_ajax, name='update_ajax'),
    path('list_info/ajax/', views.list_info_ajax, name='list_info_ajax')
]

cmdb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('asset/',include('asset.urls')),
    path('webanalysis/',include('webanalysis.urls')),
    #path('api/',include('api.urls')),
]

user/urls.py
# encoding: utf-8

from django.urls import path
from . import views


app_name = 'user'


urlpatterns = [
    path('',views.index,name='index'),
    path('login/',views.login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('delete/',views.delete,name='delete'),
    path('user_info/',views.user_info,name='user_info'),
    path('update/',views.update,name='update'),
    path('create/',views.create,name='create'),
    path('change_password/',views.change_password,name='change_password'),
    path('create/ajax',views.create_ajax,name='create_ajax'),
    path('delete/ajax',views.delete_ajax,name='delete_ajax'),
    path('change_password_ajax/',views.change_password_ajax,name='change_password_ajax'),
    path('list/ajax',views.list_ajax,name='list_ajax')

]

webanalysis/urls.py
# encoding: utf-8

from django.urls import path
from . import views

app_name = 'webanalysis'

urlpatterns = [
    path('',views.index,name='index'),
    path('upload/',views.upload,name='upload'),
    path('dist_status_code/',views.dist_status_code,name='dist_status_code'),
    path('trend_visit/',views.trend_visit,name='trend_visit')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'DataTables-1.10.15/media/css/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'DataTables-1.10.15/media/css/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'sweetalert-1.0.1/dist/sweetalert.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'common.css' %}">
    {% block links %}{% endblock %}
    <style type="text/css">
      body {
        padding-top: 70px;
      }
      {% block style %}{% endblock %}
    </style>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CMDB</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="{% block nav_user %}{% endblock %}"><a href="{% url 'user:index' %}">用户管理</a></li>
            <li class="{% block nav_asset %}{% endblock %}"><a href="{% url 'asset:index' %}">资产管理</a></li>
            <li class="{% block nav_webanalysis %}{% endblock %}"><a href="{% url 'webanalysis:index' %}">web日志分析</a></li>
            <li>{% block li_create %}{% endblock %}</li>
            <li>{% block li_changepassword %}{% endblock %}</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a>当前登陆用户是:{{ request.session.user.name }}</a></li>
            <li class="active"><a href="{% url 'user:logout' %}">退出登陆</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
        <div class="jumbotron">
        {% block container %}{% endblock %}
        </div>
        <footer class="footer">
            <p>&copy; 2018 NikoZhang.</p>
        </footer>
    </div>
    {% block dialogs %}{% endblock %}
    <script type="text/javascript" src="{% static 'jquery/jquery-1.12.4.js'%}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'sweetalert-1.0.1/dist/sweetalert.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'DataTables-1.10.15/media/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'DataTables-1.10.15/media/js/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'echart/echarts.min.js' %}"></script>
    {% block scripts %}{% endblock %}
    <script type="text/javascript">
      jQuery(document).ready(function() {
        {% block js %}{% endblock %}
      });
    </script>
  </body>
</html>